### ISSUE TITLE
Platforms Category

### ISSUE THREAD

**Issue by JesperDramsch** [softwareunderground/awesome-open-geoscience#25]
We have the platform category with Open dtect. Qgis would fit in there as well. However, these also fit in seismic and geospatial respectively.

Should we put them in the seismic/geospatial categories? Platform category? Or double them and put them in both?

**Comment by JustinGOSSES** [comment]
In order of preference, I would say (1.) platform, (2.) both, then (3.) seismic/geospatial. Platforms tend to cover multiple categories, so that's what I prefer just the platform category.

**Comment by EvanBianco** [comment]
I'm leaning towards "both", IMO, if I want to see all the tools available to me in "Geospatial", I should see QGIS, GMT, etc. But if I want to see all the platforms, I should see OpendTect, and QGIS there as well.

I think this kind of redundancy is ok. If a tool fits into more than one category, so be it. 

Also, what about changing the name from platforms to "applications", or something like that? What's the word for OpendTect and QGIS in this since. They are more "products" driven my mice than by keyboard.

**Comment by JesperDramsch** [comment]
I have put a hybrid, so people have it easier to find stuff. Closing this now.
